name: Test preprocessing workflow
on:
    push:
        branches:
        - dev_* # Run on all dev branches
    pull_request:


  
jobs:
  validate-workflow:
    name: validate-workflow
    runs-on: ubuntu-latest
    steps:
        - name: Checkout # Check out a repo
          uses: actions/checkout@v2

        - name: Install packages # Install dependencies
          run: |
            cd mlcontext
            sh setup.sh
            
        - name: Download test data
          run: |
            pip install -U --no-cache-dir gdown --pre
            gdown --folder https://drive.google.com/drive/folders/19HBBf4CTguLGNpuM8jLUWWGJlwO3lTRE?usp=share_link
             
        - name: Run preprocessing
          run: |
            sh run.sh

        - name: run tests
          run: |
            pip install pytest
            pytest test_workflow.py
