name: Test preprocessing workflow
on:
    push:
        branches:
        - dev_* # Run on all dev branches
    pull_request:


  
jobs:
  validate-workflow:
    name: validate-workflow
    runs-on: ubuntu-latest
    steps:
        - name: Checkout # Check out a repo
          uses: actions/checkout@v2

        - name: Install packages # Install dependencies
          run: |
            cd mlcontext
            sh test_workflow_setup.sh
            
        - name: Download test data and model
          run: |
            pip install -U --no-cache-dir gdown --pre
            retccl_model="mlcontext/best_ckpt.pth"
            ctranspath="mlcontext/ctranspath.pth"
            gdown https://drive.google.com/uc?id=1EOqdXSkIHg2Pcl3P8S4SGB5elDylw8O2 -O $retccl_model
            gdown "https://drive.google.com/u/0/uc?id=1DoDx_70_TLj98gTf6YTXnu4tFhsFocDX&export=download" -O $ctranspath
            gdown --folder https://drive.google.com/drive/folders/19HBBf4CTguLGNpuM8jLUWWGJlwO3lTRE?usp=share_link
             
        - name: Run preprocessing
          run: |
            sh run.sh

        - name: run tests
          run: |
            singularity run mlcontext/e2e_container.sif run_test.sh
