name: Test preprocessing workflow
on:
    push:
        branches:
        - dev_* # Run on all dev branches
        - main # Run on main branch
    pull_request:
      branches:
        - main
jobs:
  validate-workflow:
    name: Validate Workflow on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-22.04'] # 'ubuntu-20.04', 'ubuntu-18.04', 'macos-11.0', 'windows-2019'
      fail-fast: false
    steps:
        - name: Checkout # Check out a repo
          uses: actions/checkout@v2

        - name: Echo OS
          run: echo "Running on ${{ matrix.os }}"

        - name: Install packages # Install dependencies
          run: |
            cd mlcontext
            sh test_workflow_setup.sh
            
        - name: Download test data and model
          run: |
            pip install -U --no-cache-dir gdown --pre
            retccl_model="mlcontext/best_ckpt.pth"
            ctranspath="mlcontext/ctranspath.pth"
            gdown https://drive.google.com/uc?id=1EOqdXSkIHg2Pcl3P8S4SGB5elDylw8O2 -O $retccl_model
            gdown "https://drive.google.com/u/0/uc?id=1DoDx_70_TLj98gTf6YTXnu4tFhsFocDX&export=download" -O $ctranspath
            gdown --folder https://drive.google.com/drive/folders/19HBBf4CTguLGNpuM8jLUWWGJlwO3lTRE?usp=share_link
             
        - name: Run preprocessing
          run: |
            singularity run mlcontext/e2e_container.sif run_wsi_norm.sh

        - name: run tests
          run: |
            singularity run mlcontext/e2e_container.sif run_test.sh
